### ISSUE TITLE
No arranca tras instalación fresh

### ISSUE THREAD

**Issue by Arrogance** [alvaro-cuesta/nerdobot#1]
Pues eso, realmente no funciona bien el bot, tras instalar todo, a la hora de arrancar, tirar error buscando el plugin 0,

Error: Cannot find module '../plugins/0'

**Comment by alvaro-cuesta** [comment]
@Arrogance, el `config.coffee` que vale es el de `develop`.

https://github.com/alvaro-cuesta/nerdobot/blob/develop/config.EXAMPLE.coffee

Casi seguro que es eso. Ejecuta la rama `develop` a poder ser, `master` no sé ni en qué estado está.
